// Code generated by protoc-gen-go. DO NOT EDIT.
// source: esmgr.proto

package esmgr

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogMetaData struct {
	PodName              string   `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodId                string   `protobuf:"bytes,2,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	NamespaceName        string   `protobuf:"bytes,3,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	NamespaceId          string   `protobuf:"bytes,4,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogMetaData) Reset()         { *m = LogMetaData{} }
func (m *LogMetaData) String() string { return proto.CompactTextString(m) }
func (*LogMetaData) ProtoMessage()    {}
func (*LogMetaData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc1047fedaf8d4aa, []int{0}
}

func (m *LogMetaData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMetaData.Unmarshal(m, b)
}
func (m *LogMetaData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMetaData.Marshal(b, m, deterministic)
}
func (m *LogMetaData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMetaData.Merge(m, src)
}
func (m *LogMetaData) XXX_Size() int {
	return xxx_messageInfo_LogMetaData.Size(m)
}
func (m *LogMetaData) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMetaData.DiscardUnknown(m)
}

var xxx_messageInfo_LogMetaData proto.InternalMessageInfo

func (m *LogMetaData) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *LogMetaData) GetPodId() string {
	if m != nil {
		return m.PodId
	}
	return ""
}

func (m *LogMetaData) GetNamespaceName() string {
	if m != nil {
		return m.NamespaceName
	}
	return ""
}

func (m *LogMetaData) GetNamespaceId() string {
	if m != nil {
		return m.NamespaceId
	}
	return ""
}

type LogItem struct {
	Timestamp            string   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogItem) Reset()         { *m = LogItem{} }
func (m *LogItem) String() string { return proto.CompactTextString(m) }
func (*LogItem) ProtoMessage()    {}
func (*LogItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc1047fedaf8d4aa, []int{1}
}

func (m *LogItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogItem.Unmarshal(m, b)
}
func (m *LogItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogItem.Marshal(b, m, deterministic)
}
func (m *LogItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogItem.Merge(m, src)
}
func (m *LogItem) XXX_Size() int {
	return xxx_messageInfo_LogItem.Size(m)
}
func (m *LogItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LogItem.DiscardUnknown(m)
}

var xxx_messageInfo_LogItem proto.InternalMessageInfo

func (m *LogItem) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *LogItem) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LogEntry struct {
	MetaData             *LogMetaData `protobuf:"bytes,1,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	LogItems             []*LogItem   `protobuf:"bytes,2,rep,name=log_items,json=logItems,proto3" json:"log_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc1047fedaf8d4aa, []int{2}
}

func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (m *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(m, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetMetaData() *LogMetaData {
	if m != nil {
		return m.MetaData
	}
	return nil
}

func (m *LogEntry) GetLogItems() []*LogItem {
	if m != nil {
		return m.LogItems
	}
	return nil
}

type LogAppRequest struct {
	ReqId                string   `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Keywords             []string `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	StartTime            uint64   `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              uint64   `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogAppRequest) Reset()         { *m = LogAppRequest{} }
func (m *LogAppRequest) String() string { return proto.CompactTextString(m) }
func (*LogAppRequest) ProtoMessage()    {}
func (*LogAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc1047fedaf8d4aa, []int{3}
}

func (m *LogAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogAppRequest.Unmarshal(m, b)
}
func (m *LogAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogAppRequest.Marshal(b, m, deterministic)
}
func (m *LogAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogAppRequest.Merge(m, src)
}
func (m *LogAppRequest) XXX_Size() int {
	return xxx_messageInfo_LogAppRequest.Size(m)
}
func (m *LogAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogAppRequest proto.InternalMessageInfo

func (m *LogAppRequest) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *LogAppRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *LogAppRequest) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *LogAppRequest) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *LogAppRequest) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type LogAppResponse struct {
	ReqId                string      `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Code                 int32       `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string      `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	LogDetails           []*LogEntry `protobuf:"bytes,4,rep,name=log_details,json=logDetails,proto3" json:"log_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LogAppResponse) Reset()         { *m = LogAppResponse{} }
func (m *LogAppResponse) String() string { return proto.CompactTextString(m) }
func (*LogAppResponse) ProtoMessage()    {}
func (*LogAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc1047fedaf8d4aa, []int{4}
}

func (m *LogAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogAppResponse.Unmarshal(m, b)
}
func (m *LogAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogAppResponse.Marshal(b, m, deterministic)
}
func (m *LogAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogAppResponse.Merge(m, src)
}
func (m *LogAppResponse) XXX_Size() int {
	return xxx_messageInfo_LogAppResponse.Size(m)
}
func (m *LogAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogAppResponse proto.InternalMessageInfo

func (m *LogAppResponse) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *LogAppResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LogAppResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LogAppResponse) GetLogDetails() []*LogEntry {
	if m != nil {
		return m.LogDetails
	}
	return nil
}

type LogPodRequest struct {
	ReqId                string   `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	PodName              string   `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Keywords             []string `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	StartTime            uint64   `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              uint64   `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogPodRequest) Reset()         { *m = LogPodRequest{} }
func (m *LogPodRequest) String() string { return proto.CompactTextString(m) }
func (*LogPodRequest) ProtoMessage()    {}
func (*LogPodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc1047fedaf8d4aa, []int{5}
}

func (m *LogPodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogPodRequest.Unmarshal(m, b)
}
func (m *LogPodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogPodRequest.Marshal(b, m, deterministic)
}
func (m *LogPodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogPodRequest.Merge(m, src)
}
func (m *LogPodRequest) XXX_Size() int {
	return xxx_messageInfo_LogPodRequest.Size(m)
}
func (m *LogPodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogPodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogPodRequest proto.InternalMessageInfo

func (m *LogPodRequest) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *LogPodRequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *LogPodRequest) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *LogPodRequest) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *LogPodRequest) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type LogPodResponse struct {
	ReqId                string    `protobuf:"bytes,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Code                 int32     `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string    `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	LogDetails           *LogEntry `protobuf:"bytes,4,opt,name=log_details,json=logDetails,proto3" json:"log_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogPodResponse) Reset()         { *m = LogPodResponse{} }
func (m *LogPodResponse) String() string { return proto.CompactTextString(m) }
func (*LogPodResponse) ProtoMessage()    {}
func (*LogPodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc1047fedaf8d4aa, []int{6}
}

func (m *LogPodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogPodResponse.Unmarshal(m, b)
}
func (m *LogPodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogPodResponse.Marshal(b, m, deterministic)
}
func (m *LogPodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogPodResponse.Merge(m, src)
}
func (m *LogPodResponse) XXX_Size() int {
	return xxx_messageInfo_LogPodResponse.Size(m)
}
func (m *LogPodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogPodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogPodResponse proto.InternalMessageInfo

func (m *LogPodResponse) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *LogPodResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LogPodResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LogPodResponse) GetLogDetails() *LogEntry {
	if m != nil {
		return m.LogDetails
	}
	return nil
}

func init() {
	proto.RegisterType((*LogMetaData)(nil), "esmgr.LogMetaData")
	proto.RegisterType((*LogItem)(nil), "esmgr.LogItem")
	proto.RegisterType((*LogEntry)(nil), "esmgr.LogEntry")
	proto.RegisterType((*LogAppRequest)(nil), "esmgr.LogAppRequest")
	proto.RegisterType((*LogAppResponse)(nil), "esmgr.LogAppResponse")
	proto.RegisterType((*LogPodRequest)(nil), "esmgr.LogPodRequest")
	proto.RegisterType((*LogPodResponse)(nil), "esmgr.LogPodResponse")
}

func init() { proto.RegisterFile("esmgr.proto", fileDescriptor_dc1047fedaf8d4aa) }

var fileDescriptor_dc1047fedaf8d4aa = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xc1, 0x8b, 0xd3, 0x40,
	0x14, 0xc6, 0x37, 0x4d, 0xb3, 0x4d, 0x5e, 0xdc, 0xba, 0x0c, 0x2e, 0xc4, 0x45, 0xa1, 0x06, 0x84,
	0x82, 0xb0, 0x4a, 0x3d, 0x79, 0xac, 0xec, 0x1e, 0x0a, 0x59, 0x59, 0x82, 0xf7, 0x32, 0xee, 0x3c,
	0xc6, 0x60, 0x27, 0x33, 0x9d, 0x19, 0x91, 0x9e, 0x3c, 0x7b, 0xf0, 0xec, 0xbf, 0x2b, 0x33, 0xd3,
	0x26, 0x59, 0x41, 0xf6, 0xd4, 0xdb, 0xe4, 0x7d, 0xef, 0x3d, 0xbe, 0xef, 0xc7, 0x23, 0x90, 0xa3,
	0x11, 0x5c, 0x5f, 0x29, 0x2d, 0xad, 0x24, 0x89, 0xff, 0x28, 0x7f, 0x45, 0x90, 0x57, 0x92, 0xdf,
	0xa2, 0xa5, 0xd7, 0xd4, 0x52, 0xf2, 0x1c, 0x52, 0x25, 0xd9, 0xba, 0xa5, 0x02, 0x8b, 0x68, 0x16,
	0xcd, 0xb3, 0x7a, 0xa2, 0x24, 0xfb, 0x44, 0x05, 0x92, 0x0b, 0x38, 0x75, 0x52, 0xc3, 0x8a, 0x91,
	0x17, 0x12, 0x25, 0xd9, 0x8a, 0x91, 0xd7, 0x30, 0x75, 0xdd, 0x46, 0xd1, 0x7b, 0x0c, 0x73, 0xb1,
	0x97, 0xcf, 0xba, 0xaa, 0x9f, 0x7e, 0x05, 0x4f, 0xfa, 0xb6, 0x86, 0x15, 0x63, 0xdf, 0x94, 0x77,
	0xb5, 0x15, 0x2b, 0x3f, 0xc0, 0xa4, 0x92, 0x7c, 0x65, 0x51, 0x90, 0x17, 0x90, 0xd9, 0x46, 0xa0,
	0xb1, 0x54, 0xa8, 0xbd, 0x8f, 0xbe, 0x40, 0xce, 0x21, 0x16, 0x86, 0xef, 0x6d, 0xb8, 0x67, 0xf9,
	0x15, 0xd2, 0x4a, 0xf2, 0x9b, 0xd6, 0xea, 0x1d, 0x79, 0x0b, 0x99, 0x40, 0x4b, 0xd7, 0x8c, 0x5a,
	0xea, 0x67, 0xf3, 0x05, 0xb9, 0x0a, 0xd1, 0x07, 0x49, 0xeb, 0x54, 0x1c, 0x32, 0xbf, 0x81, 0x6c,
	0x23, 0xf9, 0xba, 0xb1, 0x28, 0x4c, 0x31, 0x9a, 0xc5, 0xf3, 0x7c, 0x31, 0xed, 0x07, 0x9c, 0x9f,
	0x3a, 0xdd, 0x84, 0x87, 0x29, 0xff, 0x44, 0x70, 0x56, 0x49, 0xbe, 0x54, 0xaa, 0xc6, 0xed, 0x77,
	0x34, 0xd6, 0x71, 0xd1, 0xb8, 0x75, 0x99, 0x82, 0xd1, 0x44, 0xe3, 0x76, 0xc5, 0x1c, 0x49, 0xaa,
	0x54, 0x20, 0x12, 0x9c, 0x4e, 0xa8, 0x52, 0x9e, 0xc5, 0x25, 0xa4, 0xdf, 0x70, 0xf7, 0x43, 0x6a,
	0x66, 0x8a, 0x78, 0x16, 0xcf, 0xb3, 0xba, 0xfb, 0x26, 0x2f, 0x01, 0x8c, 0xa5, 0xda, 0xae, 0x5d,
	0x5c, 0x4f, 0x69, 0x5c, 0x67, 0xbe, 0xf2, 0xb9, 0x11, 0xe8, 0xb6, 0x62, 0xcb, 0x82, 0x98, 0x78,
	0x71, 0x82, 0x2d, 0x73, 0x52, 0xf9, 0x13, 0xa6, 0x07, 0x63, 0x46, 0xc9, 0xd6, 0xe0, 0xff, 0x9c,
	0x11, 0x18, 0xdf, 0x4b, 0x16, 0x5c, 0x25, 0xb5, 0x7f, 0x1f, 0x90, 0xc6, 0x1d, 0x52, 0xf2, 0x0e,
	0x72, 0x47, 0x85, 0xa1, 0xa5, 0xcd, 0xc6, 0x14, 0x63, 0xcf, 0xe5, 0x69, 0xcf, 0xc5, 0xc3, 0xae,
	0x61, 0x23, 0xf9, 0x75, 0x68, 0x39, 0xa0, 0xb9, 0x93, 0xec, 0x71, 0x34, 0xdd, 0x91, 0x8d, 0x1e,
	0x1e, 0xd9, 0x31, 0xd1, 0x78, 0x63, 0x47, 0x41, 0x13, 0x3d, 0x82, 0x66, 0xf1, 0x3b, 0x82, 0xe4,
	0xc6, 0xdc, 0x72, 0x4d, 0x96, 0x70, 0x5e, 0x35, 0xc6, 0x56, 0x92, 0x7f, 0xdc, 0x2d, 0xf7, 0xf7,
	0xf0, 0xac, 0x1f, 0xed, 0xef, 0xea, 0xf2, 0xe2, 0x9f, 0x6a, 0x70, 0x5e, 0x9e, 0x3c, 0x58, 0x71,
	0xb7, 0xe7, 0x36, 0x58, 0xd1, 0xf3, 0x1f, 0xae, 0x18, 0x84, 0x2f, 0x4f, 0xbe, 0x9c, 0xfa, 0x9f,
	0xc0, 0xfb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x33, 0x68, 0xcf, 0xbf, 0x13, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EsMgrClient is the client API for EsMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EsMgrClient interface {
	ListLogByAppName(ctx context.Context, in *LogAppRequest, opts ...grpc.CallOption) (*LogAppResponse, error)
	ListLogByPodName(ctx context.Context, in *LogPodRequest, opts ...grpc.CallOption) (*LogPodResponse, error)
}

type esMgrClient struct {
	cc *grpc.ClientConn
}

func NewEsMgrClient(cc *grpc.ClientConn) EsMgrClient {
	return &esMgrClient{cc}
}

func (c *esMgrClient) ListLogByAppName(ctx context.Context, in *LogAppRequest, opts ...grpc.CallOption) (*LogAppResponse, error) {
	out := new(LogAppResponse)
	err := c.cc.Invoke(ctx, "/esmgr.EsMgr/ListLogByAppName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *esMgrClient) ListLogByPodName(ctx context.Context, in *LogPodRequest, opts ...grpc.CallOption) (*LogPodResponse, error) {
	out := new(LogPodResponse)
	err := c.cc.Invoke(ctx, "/esmgr.EsMgr/ListLogByPodName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EsMgrServer is the server API for EsMgr service.
type EsMgrServer interface {
	ListLogByAppName(context.Context, *LogAppRequest) (*LogAppResponse, error)
	ListLogByPodName(context.Context, *LogPodRequest) (*LogPodResponse, error)
}

func RegisterEsMgrServer(s *grpc.Server, srv EsMgrServer) {
	s.RegisterService(&_EsMgr_serviceDesc, srv)
}

func _EsMgr_ListLogByAppName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsMgrServer).ListLogByAppName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/esmgr.EsMgr/ListLogByAppName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsMgrServer).ListLogByAppName(ctx, req.(*LogAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EsMgr_ListLogByPodName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogPodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EsMgrServer).ListLogByPodName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/esmgr.EsMgr/ListLogByPodName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EsMgrServer).ListLogByPodName(ctx, req.(*LogPodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EsMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "esmgr.EsMgr",
	HandlerType: (*EsMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLogByAppName",
			Handler:    _EsMgr_ListLogByAppName_Handler,
		},
		{
			MethodName: "ListLogByPodName",
			Handler:    _EsMgr_ListLogByPodName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "esmgr.proto",
}
