apiVersion: v1
kind: Service
metadata:
  name: logmgr
  namespace: logging
  labels:
    app: logmgr
spec:
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: logmgr
