apiVersion: v1
kind: Service
metadata:
  name: logmgr
  labels:
    app: logmgr
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: pgrpc
      port: 50052
      targetPort: 50052
      protocol: TCP
    - name: prometheus
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: logmgr
  type: LoadBalancer
